name: nginxpm
version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    # Uncomment the next line if you uncomment anything in the section
    # environment:
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    x-casaos:
      ports:
        - container: "80"
          description:
            en_us: "http"
        - container: "443"
          description:
            en_us: "https"
      volumes:
        - container: /data
          description:
            en_us: ""
    container_name: nginxpm
x-casaos:
  architectures:
    - amd64
  main: nginxpm
  author: CasaOS Team
  category: Network
  description:
    en_us: Easily forward to your websites running at home or otherwise, including free SSL, without having to know too much about Nginx or Letsencrypt.
  developer: jc21
  tagline:
    en_us: Expose your services easily and securely
  tips: {}
  title:
    en_us: nginxpm
  index: /